Navigator/Navigator/Models/DataModels/Object.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Navigator.Models.DataModels
{
    public class Object
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public bool? Repaired { get; set; }

        public string Number { get; set; }


        public virtual ICollection<Object> Objects { get; set; }
        
        [Required]
        public virtual Level Level { get; set; }

        [Required]
        public virtual Building Building { get; set; }
        
        [Required]
        public virtual TypeObject TypeObject { get; set; }

        [Required]
        public virtual Node Node { get; set; }
    }
}

Navigator/Navigator/Models/DataModels/TypeObject.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Navigator.Models.DataModels
{
    public class TypeObject
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public virtual ICollection<Object> Objects { get; set; }
    }
}

Navigator/Navigator/Models/Sourceseed/LevelsInitializer.cs
using Navigator.Models.DataModels;

namespace Navigator.Models.Sourceseed
{
    public class LevelsInitializer
    {
        public static Level[] Initialize()
        {
            return new Level[]
            {
                new Level{Id=1, Name=1},
                new Level{Id=2, Name=2}
            };
        }
    }
}

Navigator/Navigator/ViewModels/ItemVm.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Navigator.ViewModels
{
    public class ItemVm
    {
        public Guid ItemId { get; set; }

        public string Number { get; set; }

        public string Description { get; set; }

        public IEnumerable<PointVm> Border { get; set; }
        public string BorderString => string.Join(" ", Border.Select(x => x.ToString()));
    }
}

Navigator/Navigator/ViewModels/MainMapVm.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Navigator.ViewModels
{
    public class MainMapVm
    {
        public Guid LevelId { get; set; }

        public IEnumerable<PointVm> Border { get; set; }
        public string BorderString => string.Join(" ", Border.Select(x => x.ToString()));

        public IEnumerable<ItemVm> Rooms { get; set; }

        public IEnumerable<ItemVm> Stairs { get; set; }
    }
}

Navigator/Navigator/ViewModels/PointVm.cs
namespace Navigator.ViewModels
{
    public class PointVm
    {
        public int X { get; set; }

        public int Y { get; set; }

        public PointVm(int x, int y)
        {
            X = x;
            Y = y;
        }

        public override string ToString()
        {
            return $"{X},{Y}";
        }
    }
}

Navigator/Navigator/Controllers/MainMapController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Abstractions.Interfaces;

namespace Navigator.Controllers
{
    public class MainMapController : Controller
    {
        private readonly IMainMapService _mainMapService;

        public MainMapController()
        {
            _mainMapService = DependencyResolver.Current.GetService<IMainMapService>();
        }

        // GET: MainMap
        public ActionResult MainMap()
        {
            var model = _mainMapService.GetMainMap();
            return View(model);
        }

        public ActionResult GetMapPv(Guid? levelId = null)
        {
            var model = _mainMapService.GetMainMap(levelId);
            return View(model);
        }

        // Метод для проверки Ajax-запросов

        public ActionResult Get(List<string> items)
        {
            //var startId = _mainMapService.GetItemId(items[0]);
            //var finishId = _mainMapService.GetItemId(items[1]);

            return PartialView();
        }
        
        //public ActionResult Get(string value, string type)
        //{
        //    return PartialView();
        //}

        public ActionResult SearchPath(string fromItem, string toItem)
        {
            var path = _mainMapService.GetPath(fromItem, toItem);
            return PartialView(path);
        }
    }
}

Navigator/Navigator/Views/Home/Index.cshtml
<!-- <div class="main-div"> -->
<header>
    <div class="header-div">
        <!--Логотип-->
        <img src="/Content/img/logo.svg" alt="Логотип" class="logo">

        <!--Поле поиска с кнопками-->
        <div class="search-div flex-itm">
            <div class="input-div">
                <input type="text" id="search-from" class="search-from" placeholder="Откуда">
                <button id="change-btn" class="change-btn">
                    <img src="/Content/img/change.svg" alt="Поменять" class="change-img">
                </button>
                <input type="text" id="search-to" class="search-to" placeholder="Куда">
            </div>
            <div class="btn-div">
                <button id="search-btn" class="btn search-btn primary-btn">Поиск</button>
                <button id="btn-reset" class="btn reset-btn">Сбросить</button>
            </div>
        </div>
    </div>
</header>
<main>
    <div class="levels-div">
        <span class="levels-span">Этаж:</span>
        <button class="level-btn">1</button>
        <button class="level-btn">2</button>
        <button class="level-btn">3</button>
    </div>
    <!-- <img src="/Content/img/russia.svg" alt="" class="maps"> -->
    <!-- viewBox="0 0 400 400" -->
    <div class="primer">
        <svg>
            <rect x="7%" y="7%" />
            <rect x="28%" y="28%" />
            <rect x="50%" y="50%" />
            <rect x="72%" y="72%" />

            <rect x="72%" y="7%" />
            <rect x="50%" y="28%" />
            <rect x="28%" y="50%" />
            <rect x="7%" y="72%" />
        </svg>
    </div>
    <!-- <object type="image/svg+xml" data="/Content/img/russia.svg" id="object"></object> -->
</main>
<footer>
    <div class="footer-div">
        <img src="/Content/img/logo.svg" alt="Логотип" class="logo flex-itm">
        <div class="social-links">
            <a href="https://mpei.ru/Pages/default.aspx" target="_blank" class="social-link">Официальный сайт</a>
            <a href="http://profcom.mpei.ru/" target="_blank" class="social-link">Профком студентов</a>
            <a href="https://vk.com/overhear_first_energy" target="_blank" class="social-link">Подслушано МЭИ</a>
        </div>
    </div>
</footer>
<!-- </div> -->

Navigator/Navigator/Views/MainMap/GetMapPv.cshtml
@model Abstractions.ViewModels.MainMapVm

<main id="main">
    <div class="levels-div">
        <span class="levels-span">Этаж:</span>
        @foreach (var level in Model.AllLevels)
        {
            // Todo : добавить добавление класса, если этажи равны
            if (level.Id == Model.CurrentLevelId)
            {
                <button class="level-btn currentLevel" type="submit">
                    @Ajax.ActionLink(level.Number.ToString(), "GetMapPv", "MainMap", new { levelId = level.Id },
                    new AjaxOptions { UpdateTargetId = "main" })
                </button>
            }
            else
            {
                //Кнопка этажа
                <button class="level-btn" type="submit">
                    @Ajax.ActionLink(level.Number.ToString(), "GetMapPv", "MainMap", new { levelId = level.Id },
                    new AjaxOptions { UpdateTargetId = "main" })
                </button>
            }
        }

        @for(int i=3;i<6;i++)
        {
            <button class="level-btn" type="submit">
                @Ajax.ActionLink(i.ToString(), "GetMapPv", "MainMap",
               new AjaxOptions { UpdateTargetId = "main" })
                </button>
        }
    </div>

    <div class="svg-div scheme" id="map">
        <svg viewBox="100 -10 1250 420">
            <polygon class="border-plg" points="@Model.BorderString" stroke="black" />
            @foreach (var stair in (Model.Stairs))
            {
                <polyline class="stairs" points="@stair.BorderString" />
                <image xlink:href="https://svgsilh.com/svg/44066-795548.svg" width="@stair.Width" height="@stair.Height" x="@stair.MinX" y="@stair.MinY" />
            }

            @foreach (var room in (Model.Rooms))
            {
                <polyline class="pl-item room" points="@room.BorderString" data-id="@room.ItemId" fill="url(#pattern2)" />
            }

            @foreach (var wall in (Model.Walls))
            {
                <polyline points="@wall.BorderString" />
            }

            @foreach (var wcM in (Model.WcMans))
            {
                <polyline class="pl-item wcM" points="@wcM.BorderString" />
            }

            @foreach (var wcW in (Model.WcWomans))
            {
                <polyline class="pl-item wcW" points="@wcW.BorderString" />
            }
            <polyline class="path" points="" />

            @*<image xlink:href="https://svgsilh.com/svg/44066-795548.svg" width="20" height="30" x="210" y="80"></image>*@

        </svg>

        @foreach (var room in (Model.Rooms))
        {
            <div class="scheme-item" data-id="@room.ItemId">

                @*Отображение названия кабинета*@
                @*<div class="scheme-name">@room.Number</div>*@
                <div class="scheme-popup">
                    <p>
                        <strong name="value">@room.Number</strong>
                        <br>
                        @room.Description
                    </p>
                    <button name="from" data-value=@room.Number>Отсюда</button>
                    <button name="to" data-value=@room.Number>Сюда</button>
                </div>
            </div>
        }
    </div>
</main>

Navigator/Navigator/Views/MainMap/GetNameSearch.cshtml
@model Abstractions.ViewModels.ItemVm

<div id="primer2">
    <h2>@Model.Description</h2>
</div>

Navigator/Navigator/Views/MainMap/MainMap.cshtml
<!-- <div class="main-div"> -->
@model Abstractions.ViewModels.MainMapVm

<header>
    <div class="header-div">
        <!--Логотип-->
        <img src="/Content/img/logo.svg" alt="Логотип" class="logo">

        <!--Поле поиска с кнопками-->
        <div class="search-div flex-itm">
            @*Форма отправки запроса в метод SearchPath и обновление тега с Id "main"*@
            @using (Ajax.BeginForm("SearchPath", new AjaxOptions { UpdateTargetId = "main" }))
            {
                <div class="input-div">
                    @*Поле для ввода пункта начала построения пути*@
                    <input type="text" id="search-from" class="search-from" placeholder="Откуда" autocomplete="off" name="fromItem" list="allItems" required>
                    @*Кнопка замены значения одного поля на другое*@
                    <button type="button" id="change-btn" class="change-btn">
                        <img src="/Content/img/change.svg" alt="Поменять" class="change-img">
                    </button>
                    @*Поле для ввода пункта окончания построения пути*@
                    <input type="text" id="search-to" class="search-to" placeholder="Куда" autocomplete="off" name="toItem" list="allItems" required>
                </div>

                @*Выпадающий список со всеми объектами*@
                <datalist id="allItems">
                    @foreach (var item in Model.AllItems)
                    {
                        <option value="@item.Number"></option>
                    }
                </datalist>
                <div class="btn-div">
                    @*Кнопка отправки*@
                    <button type="submit" id="search-btn" class="btn search-btn primary-btn">Поиск</button>
                    @*Кнопка сброса введенных данных*@
                    <button type="reset" id="btn-reset" class="btn reset-btn">Сбросить</button>
                </div>
            }
        </div>
    </div>
</header>

@Html.Partial("GetMapPv")

<footer>
    <div class="footer-div">
        @*<img src="/Content/img/logo.svg" alt="Логотип" class="logo flex-itm">*@
        <div class="social-links">
            <a href="https://mpei.ru/Pages/default.aspx" target="_blank" class="social-link">Официальный сайт</a>
            <a href="http://profcom.mpei.ru/" target="_blank" class="social-link">Профком студентов</a>
            <a href="https://vk.com/overhear_first_energy" target="_blank" class="social-link">Подслушано МЭИ</a>
        </div>
    </div>
</footer>

@{
    //Todo: добавить в bundle
}
<script src="https://snipp.ru/cdn/jquery/2.1.1/jquery.min.js"></script>

Navigator/Navigator/Views/MainMap/SearchPath.cshtml
@model Abstractions.ViewModels.PathVm
<div id="primer2">
    <div>
        @Model.Path
    </div>
    <div>
        @Model.Path.Length
    </div>
</div>

Navigator/Navigator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="Content/img/icon.svg" type="image/svg">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MpeiMaps</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    @RenderBody()
    @Scripts.Render("~/Scripts/js")
    @Scripts.Render("~/Scripts/ajax")
</body>
</html>